language: ruby
cache: bundler
rvm:
  - 2.6.3

bundler_args: --without production

script:
  - bundle exec rspec --format progress

# safelist
branches:
  only:
  - master

notifications:
  email: "snepote@gmail.com"
